default_period_ms = 1000
default_enable_udp = true
default_enable_tcp = false

mode = "random"
random_step = 0.05

# Show debugging info
verbose = false

[boards.VCU]
period_ms = 200
enable_udp = true

[boards.BCU]
period_ms = 500
enable_udp = false
