default_period_ms = 1000
default_enable_udp = true
default_enable_tcp = false

mode = "random"

# Random mode variation step
random_step = 0.1

# Show debugging info
verbose = false

[boards.VCU]
period_ms = 200
enable_udp = true

[boards.BCU]
period_ms = 500
enable_udp = false

[boards.HVSCU-Cabinet]
period_ms = 300
